### PR TITLE
Add ctrl-S save shortcut

### PR DESCRIPTION
**Pull request by Timmmm**
I haven't actually tested this yet. Because. I'm lazy. Sorry.

### CODE REVIEW

**Comment by hacdias** [comment]
Hey!

Thanks for this idea! I'll check this as soon as I can, and merge it if it's working :)

**Comment by hacdias** [comment]
There was just a missing parenthesis 😃

**Comment by hacdias** [comment]
Thanks!

**Comment by Timmmm** [comment]
Ha so close! Thanks!

**Pull request merged**
